services:
  auth_ms:
    build: .
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KTOR_REALM: ${KTOR_REALM}
    networks:
      - backend
    depends_on:
        - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  backend: